### ISSUE TITLE
[Feature] - Remove Plots per Command

### ISSUE THREAD

**Issue by straussi** [AlpsBTE/Plot-System#119]
It would be very helpful if there would be a command like
/pss plot remove <id> 
to delete a plot completely from the plot system, for example if it got created wrongly or something.
~Raphael, BTE-Germany

**Comment by LordTuxn** [comment]
There's already a command for this.

`/deleteplot <Id>`

https://github.com/AlpsBTE/Plot-System/wiki/Commands-&-Permissions#admin-commands
