### ISSUE TITLE
[Bug] - Duplicate column Plugin wont Start

### ISSUE THREAD

**Issue by SpigotFehlerYT** [AlpsBTE/Plot-System#120]
## Steps to Reproduce
1. Start server with plugin

CREATE TABLE IF NOT EXISTS `plotsystem_builders`" +
"(" +
" `uuid` varchar(36) NOT NULL ," +
" `name` varchar(16) NOT NULL ," +
" `score` int DEFAULT 0 ," +
" `completed_plots` int DEFAULT 0 ," +
----- " `third_slot` int NULL ," +
" `first_slot` int NULL ," +
" `second_slot` int NULL ," +
----- " `third_slot` int NULL ," +
"PRIMARY KEY (`uuid`)" +
");",

## Possible Solution

remove one of booth " `third_slot` int NULL ," +

**Comment by LordTuxn** [comment]
Uhh thanks for the report. I will fix it as soon as possible!

**Comment by LordTuxn** [comment]
Fixed in latest release: https://jenkins.alps-bte.com/job/PlotSystem/123/
