### ISSUE TITLE
[Bug] - Gamemode 0 when teleporting to plot

### ISSUE THREAD

**Issue by LordTuxn** [AlpsBTE/Plot-System#24]
## Description
This is a bug that happens very rarely when generating a new plot. When teleporting to the plot, the player is always be set into surivial mode.

## Steps to Reproduce
1. Generate a new plot
2. Teleport to the plot

## Possible Solution
Check for default world gamemode and update it to creative if wrong.

**Comment by LordTuxn** [comment]
Probably fixed in plot generator rework but needs some more testing

**Comment by Cinnazeyy** [comment]
Has this ever happened again since the rework?

**Comment by LordTuxn** [comment]
Don't think so

**Comment by Cinnazeyy** [comment]
Great! Ill close this issue then!
