### ISSUE TITLE
[Feature] - Config Values

### ISSUE THREAD

**Issue by LordTuxn** [AlpsBTE/Plot-System#29]
Config values which have to be implemented and added to the current config.

- [x] Add and implement option to set plot inactivity system interval
- [x] Add and implement option to set group system to enabled/disabled
- [x] Add and implement option to set "check for updates" to enabled/disabled

**Comment by Cinnazeyy** [comment]
https://github.com/AlpsBTE/Plot-System/commit/8c7a7eea32a93108918f69f612267414f1903e80
