### ISSUE TITLE
Fix Mobile Spacing

### ISSUE THREAD

**Issue by Cinnazeyy** [AlpsBTE/Plot-System#45]
Right now all of the highlighted spaces, are of different sizes. 
Would look a lot better if they were all one uniform size.
![Screenshot_20210915-163002_Chrome.jpg](https://user-images.githubusercontent.com/33779112/133453464-81d27044-a175-4275-8598-04185a798cd3.jpg)

**Comment by LordTuxn** [comment]
Wrong repo lmao

**Comment by Cinnazeyy** [comment]
😩🤡
