### ISSUE TITLE
[Feature] - Structure Void

### ISSUE THREAD

**Issue by Georg-code** [AlpsBTE/Plot-System#58]
**Is your feature request related to a problem? Please describe.**
Yes, Problem

**Describe the solution you'd like**
Add structure void

**Describe alternatives you've considered**
Barrier, but you can't walk through barriers

**Additional context**
Add to special blocks

**Comment by LordTuxn** [comment]
Added in https://github.com/AlpsBTE/Plot-System/commit/86c8be580e0263de754fbbeff56b8c49a86a9d5e
