### ISSUE TITLE
[Feature] - Add option in config to automatically save plot worlds in a seperate folder

### ISSUE THREAD

**Issue by LordTuxn** [AlpsBTE/Plot-System#68]
Bukkit has a feature, to change the directory for worlds. 
This is editable in the Bukkit.yml file by adding `settings.world-container: plots`
Advantages: More manageable and cleaner, especially with a large number of worlds.

This feature should be configurable in the config.yml. It should also move all existing worlds to the new directory.

**Comment by Zoriot** [comment]
Have been added to the wiki: [Organizing Worlds in a Separate Folder,](https://github.com/AlpsBTE/Plot-System/wiki/Organizing-Worlds-in-a-Separate-Folder)
Writing code for this isn't really needed — manual migration is in most cases completely okay.
