### ISSUE TITLE
[Feature] - Allow admins to review their own plot

### ISSUE THREAD

**Issue by StoneMcYT** [AlpsBTE/Plot-System#76]
**Is your feature request related to a problem? Please describe.**
I dont think im the only one faced with this but your a admin building on the plot system and you submit and realize you gotta ask another admin to get online to approve your build

**Describe the solution you'd like**
Allow people with the plotsystem.review.* permission node to review their own plots.
**Describe alternatives you've considered**
NIL
**Additional context**
NIL

**Comment by NApartas** [comment]
We disabled this because we want a fair Plotsystem for everyone. You are way too biased reviewing your own plot. Waiting for another admin/reviewer really is not a problem.

**Comment by Cinnazeyy** [comment]
We could enable self-reviewing for admins, if the dev-mode is true, dont think I want to enable this for production use tho

**Comment by LordTuxn** [comment]
We could add a config option, but I also think that the dev-mode is the better solution..

**Comment by NApartas** [comment]
Absolutely. For testing purposes it could be quite handsome

**Comment by LordTuxn** [comment]
Implemented in https://github.com/AlpsBTE/Plot-System/commit/ce2311684eda4b3947085fa7f6c3349ef84129da
