### ISSUE TITLE
[Feature] - Add settings menu

### ISSUE THREAD

**Issue by MineFact** [AlpsBTE/Plot-System#86]
**Is your feature request related to a problem? Please describe.**
There is a settings item in the Companion but it has no functionality yet.

**Describe the solution you'd like**
Implement a working settings menu and system

**Additional context**

![image](https://user-images.githubusercontent.com/66020920/156351282-cf751393-4012-4e21-bf39-e03b5e558d01.png)

**Comment by LordTuxn** [comment]
I have already started implementing the settings menu in the multi-language branch, as we need it there as well. We should probably complete and merge the multi-language system first.

https://github.com/AlpsBTE/Plot-System/blob/accba344076ebcddcdb2c6a84dad254b93b14e4f/src/main/java/com/alpsbte/plotsystem/core/menus/SettingsMenu.java

**Comment by LordTuxn** [comment]
Implemented in https://github.com/AlpsBTE/Plot-System/pull/62
