### ISSUE TITLE
An error occurred while placing player slot items! java.lang.NullPointerException: null

### ISSUE THREAD

**Issue by StoneMcYT** [AlpsBTE/Plot-System#88]
Logs are attached as a link

in game screenshot 
![image](https://user-images.githubusercontent.com/67421882/158999018-9e6dcb58-103a-4ebb-ab7d-d0c1a0958f26.png)

Database for builders
![image](https://user-images.githubusercontent.com/67421882/158999048-776bd877-713c-4ce8-86c4-9f42607e63b4.png)

https://pastebin.com/PXks3ZCi

**Comment by Cinnazeyy** [comment]
Are those slot columns' default values actually "0" or is that just your program displaying "null" as "0"?

**Comment by StoneMcYT** [comment]
> Are those slot columns' default values actually "0" or is that just your program displaying "null" as "0"?
I just opened up terminal and yes it seams like those values are 0
![image](https://user-images.githubusercontent.com/67421882/159000899-74d9a76e-8982-4ffc-ae78-853e46369071.png)

**Comment by LordTuxn** [comment]
Looks like there is a problem with default values in the SQL statements...

**Comment by LordTuxn** [comment]
specifically with default NULL values

**Comment by StoneMcYT** [comment]
> specifically with default NULL values

if i infer correctly the values should all be (NULL), that may have been my program changing the values when i was manually setting the lang column

**Comment by StoneMcYT** [comment]
![image](https://user-images.githubusercontent.com/67421882/159003111-19517beb-4d1c-4571-b2d6-739068cac8b4.png)
Issue has been fixed after manually setting all the 0's to (NULL)
