### ISSUE TITLE
[Feature] - Database expansion

### ISSUE THREAD

**Issue by Cinnazeyy** [AlpsBTE/Plot-System#97]
**Implement support for the following new tables:** 
* api_keys
* plotsystem_buildteams
* plotsystem_builder_is_reviewer
* plotsystem_buildteam_has_countries

**As well as add support for the following new colum in table "plotsystem_countries":**
* continent

[Link to whole updated database scheme](https://media.discordapp.net/attachments/916742538847748126/961716721704636486/unknown.png?width=1209&height=676)

**Also keep in mind backwards compatibility!**

**Comment by jokil123** [comment]
api_keys was renamed to plotsystem_api_keys.
the current database model should look like this:
https://github.com/AlpsBTE/Plot-System-API/blob/main/migrations/20220517070321_database_schema_setup.sql
